# Generated by Django 5.0.7 on 2025-09-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_login_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('des', models.CharField(max_length=100)),
            ],
        ),
    ]
