# Generated by Django 5.0.7 on 2025-09-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=1)),
                ('quiz_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_title', to='api.coursecard')),
            ],
        ),
    ]
