# Generated by Django 5.0.7 on 2025-09-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('quiz_ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question', to='api.quiz')),
            ],
        ),
    ]
