# Generated by Django 5.0.7 on 2025-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_result_course_head_result_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
